name: Google Cloud Run Java CD
on: [ push, pull_request ]

env:
  GCLOUD_PROJECT_ID: piotr-main
  GCLOUD_REGION: europe-central2
  GCLOUD_GCR: eu.gcr.io
  DOCKER_IMAGE: eu.gcr.io/piotr-main/simply-silly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 117
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
      - name: Docker Login
        run: |
          gcloud auth configure-docker
      - name: Build And Push Docker Image
        run: |
          ./gradlew check dockerPush --no-daemon
